stages:
  - deploy

deploy:
  stage: deploy
  script:
    - php artisan migrate --force
    - php artisan contract:setup-counter
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
  only:
    - main
